"""testing relationships

Revision ID: 16ca85ebaf6e
Revises: d07dc3dc0406
Create Date: 2022-11-15 12:23:54.627264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ca85ebaf6e'
down_revision = 'd07dc3dc0406'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('customers', sa.Column('customer_name', sa.String(length=50), nullable=True))
    op.drop_column('customers', 'company_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('company_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('customers', 'customer_name')
    op.alter_column('contacts', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
