"""removed bad relationship

Revision ID: 1e9e954821c3
Revises: 414aec58e86c
Create Date: 2022-11-16 13:29:10.707587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9e954821c3'
down_revision = '414aec58e86c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
