"""removed nullable2

Revision ID: 206f7ebfead0
Revises: bcfd7fbb962e
Create Date: 2022-11-28 09:34:33.010599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206f7ebfead0'
down_revision = 'bcfd7fbb962e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
