"""test3

Revision ID: 59a4a668ffd2
Revises: 6cc70b3f07a4
Create Date: 2022-11-17 09:07:44.064605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a4a668ffd2'
down_revision = '6cc70b3f07a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
