"""test2

Revision ID: 6cc70b3f07a4
Revises: c12ea88c8bb7
Create Date: 2022-11-17 09:04:25.815402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc70b3f07a4'
down_revision = 'c12ea88c8bb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'contacts', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='unique')
    # ### end Alembic commands ###
