"""one more fix

Revision ID: c12ea88c8bb7
Revises: f0329aca1ebe
Create Date: 2022-11-16 15:58:10.288511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12ea88c8bb7'
down_revision = 'f0329aca1ebe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
