"""test

Revision ID: cbf59f759fbc
Revises: 1e9e954821c3
Create Date: 2022-11-16 13:44:06.623384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf59f759fbc'
down_revision = '1e9e954821c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notes_ticket_id_fkey', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tickets_customer_id_fkey', 'tickets', type_='foreignkey')
    op.drop_constraint('tickets_tech_id_fkey', 'tickets', type_='foreignkey')
    op.drop_constraint('tickets_user_id_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'contacts', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tickets', 'techs', ['tech_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tickets', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_user_id_fkey', 'tickets', 'contacts', ['user_id'], ['id'])
    op.create_foreign_key('tickets_tech_id_fkey', 'tickets', 'techs', ['tech_id'], ['id'])
    op.create_foreign_key('tickets_customer_id_fkey', 'tickets', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_ticket_id_fkey', 'notes', 'tickets', ['ticket_id'], ['id'])
    # ### end Alembic commands ###
