"""test4

Revision ID: d77b9ef6a10e
Revises: 59a4a668ffd2
Create Date: 2022-11-17 09:09:05.639348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77b9ef6a10e'
down_revision = '59a4a668ffd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
