"""checkin

Revision ID: f0329aca1ebe
Revises: cbf59f759fbc
Create Date: 2022-11-16 15:33:03.147807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0329aca1ebe'
down_revision = 'cbf59f759fbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
